# This is a basic workflow to help you get started with Actions

name: Auto Update Country Data

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '26 21 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install prerequisites
      - name: Installing prerequisites
        run: sudo apt-get install python3-pip jq && sudo pip3 install yq

      # Update country data
      - name: Auto Update Country Data
        run: .github/workflows/auto-update.sh
